title       = "danviet"
baseURL     = "https://danviet-cli.tamnd.com/"
description = "A command line for danviet."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/danviet-cli"
